@baseUrl = http://localhost:3000/categories

POST {{baseUrl}}/create-category HTTP/1.1
Content-Type: application/json

{
    "name": "Electronics",
    "parent_category_id": null
}

###
POST {{baseUrl}}/create-category HTTP/1.1
Content-Type: application/json

{
    "name": "Accessories",
    "parent_category_id": 1
}

###
POST {{baseUrl}}/create-category HTTP/1.1
Content-Type: application/json

{
    "name": "Wearable Accessories",
    "parent_category_id": 7
}

###
POST {{baseUrl}}/create-category HTTP/1.1
Content-Type: application/json

{
    "name": "Smart Watch",
    "parent_category_id": 8
}

###
GET {{baseUrl}}/

###
GET {{baseUrl}}/5

###
PUT {{baseUrl}}/update-category/2 HTTP/1.1
Content-Type: application/json

{
    "name": "Accessories",
    "parent_category_id": 1
}

###
DELETE {{baseUrl}}/delete-category/2 HTTP/1.1
Content-Type: application/json

###
PATCH {{baseUrl}}/deactivate/7
Content-Type: application/json

{
  "is_active": 0
}